POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "username": "abdulqadir",
    "password": "Pass1234!"
}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
    "username": "abdulqadir",
    "password": "Pass1234!",
    "email": "qadirmsingi007@gmail.com"
}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
# Authorization: Token 93804652f283baf214ba19d65d1400638834b1a5

{}
