# Generated by Django 4.2.14 on 2024-07-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shehitaa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
