# Generated by Django 4.2.14 on 2024-07-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shehitaa', '0002_remove_product_available'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
