# Generated by Django 4.2.14 on 2024-07-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shehitaa', '0003_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
