# Generated by Django 4.2.14 on 2024-07-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shehitaa', '0004_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
